version: 2
jobs:
  build:
    docker:
      - image: debian:bullseye

    steps:
      - checkout
      - run:
          name: Install Git
          command: 'apt-get update && apt-get install -qy git'
      - checkout
      - add_ssh_keys: # machine user
          fingerprints: "Fingerprint from SSH Permissions"
      - run:
          name: Install Submodules
          command: git submodule sync && git submodule update --init
      - run:
          name: Install sudo
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Install GCC
          command: 'sudo apt-get update -qq && sudo apt-get install -qq g++-7 && sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90'
          
      - run:
          name: Install CMake
          command: 'apt-get update && sudo apt-get install -y cmake'
      - run:
          name: Create build files
          command: 'mkdir build ; cd build ; cmake ..'
      - run:
          name: Versions
          command: 'g++ --version ; uname -a'
      - run:
          name: Compile
          command: 'cmake --build build'
