#pragma once

#include "staticBase.h"
#include "logCore.h"
#include <iostream>

#ifdef _WIN32
#define COLOR(ID) ("\x1b[1;" #ID "m")
#else
#define COLOR(ID) ("\x1b[" #ID "m")
#endif

FASTLOG_BEGIN
COLOR_BEGIN

FSTL_STATIC_CONSTEXPR RESET_COLOR    = COLOR(0);
FSTL_STATIC_CONSTEXPR BLACK			 = COLOR(30);
FSTL_STATIC_CONSTEXPR RED			 = COLOR(31);
FSTL_STATIC_CONSTEXPR GREEN			 = COLOR(32);
FSTL_STATIC_CONSTEXPR YELLOW		 = COLOR(33);
FSTL_STATIC_CONSTEXPR BLUE			 = COLOR(34);
FSTL_STATIC_CONSTEXPR MAGENTA		 = COLOR(35);
FSTL_STATIC_CONSTEXPR CYAN			 = COLOR(36);
FSTL_STATIC_CONSTEXPR WHITE			 = COLOR(37);
FSTL_STATIC_CONSTEXPR LIGHT_GRAY	 = COLOR(90);
FSTL_STATIC_CONSTEXPR LIGHT_RED		 = COLOR(91);
FSTL_STATIC_CONSTEXPR LIGHT_GREEN	 = COLOR(92);
FSTL_STATIC_CONSTEXPR LIGHT_YELLOW	 = COLOR(93);
FSTL_STATIC_CONSTEXPR LIGHT_BLUE	 = COLOR(94);
FSTL_STATIC_CONSTEXPR LIGHT_MAGENTA	 = COLOR(95);
FSTL_STATIC_CONSTEXPR LIGHT_CYAN	 = COLOR(96);
FSTL_STATIC_CONSTEXPR LIGHT_WHITE	 = COLOR(97);

COLOR_END
FASTLOG_END