name: build(D)

on:
  push:
    branches:
      - development

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: prepare
      run: mkdir build
    - name: Checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: configure
      run: cd build && cmake -DCMAKE_BUILD_TYPE=debug ..
    - name: cmake
      run: cd build ; cmake ..
    - name: build
      run: make -C build


  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
          submodules: true
    - name: configure
      run: |
        mkdir build
        cd build
        cmake ..
    - name: build
      run: cmake --build build
